keys:
  - &nixosVMWareMinimal age1aj8nwyxg6kh5j8f8s4l6agr0vr424w27xs69tttgykwmpu3z2uts8xclpd
  - &nixosVMWareGnome age1vdjxrusgxffte8tunpxyszm7fnrewfuedkkwx8y6e2fcwas5ketqszhxpr
  - &nixosVBoxMinimal age1vg88j3dc6ja4vt4dmyqpz0ljxq77q37tq53zz44k8dxe82vc8eus7hghfc
  - &nixosVBoxGnome age1vg88j3dc6ja4vt4dmyqpz0ljxq77q37tq53zz44k8dxe82vc8eus7hghfc
  - &nixosX360 age19cknes4sytvdsm4203ys6pttyhjw9h4d0ehlr35a07vrc6zvsd7qvhvkre
  - &nixosASUS age12770nz20z57awadcze6jgu62uqpfscvux6x0vaf3zd2xxmjzde3sgs0e8n
  - &nixosDellXPS age1vdjxrusgxffte8tunpxyszm7fnrewfuedkkwx8y6e2fcwas5ketqszhxpr
creation_rules:
  - path_regex: secrets/root-secrets.yaml
    key_groups:
    - age:
      - *nixosVMWareMinimal
      - *nixosVMWareGnome
      - *nixosVBoxMinimal
      - *nixosVBoxGnome
      - *nixosX360
      - *nixosASUS
      - *nixosDellXPS
