# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."passbolt-db" = {
    image = "mariadb:10.11";
    environment = {
      "MYSQL_DATABASE" = "passbolt";
      "MYSQL_PASSWORD" = "P4ssb0lt";
      "MYSQL_RANDOM_ROOT_PASSWORD" = "true";
      "MYSQL_USER" = "passbolt";
    };
    volumes = [
      "passbolt_database_volume:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=passbolt_default"
    ];
  };
  systemd.services."podman-passbolt-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-passbolt_default.service"
      "podman-volume-passbolt_database_volume.service"
    ];
    requires = [
      "podman-network-passbolt_default.service"
      "podman-volume-passbolt_database_volume.service"
    ];
    partOf = [
      "podman-compose-passbolt-root.target"
    ];
    wantedBy = [
      "podman-compose-passbolt-root.target"
    ];
  };
  virtualisation.oci-containers.containers."passbolt-passbolt" = {
    image = "passbolt/passbolt:latest-ce";
    environment = {
      "APP_FULL_BASE_URL" = "https://nixostranfor.local:444";
      "DATASOURCES_DEFAULT_DATABASE" = "passbolt";
      "DATASOURCES_DEFAULT_HOST" = "db";
      "DATASOURCES_DEFAULT_PASSWORD" = "P4ssb0lt";
      "DATASOURCES_DEFAULT_USERNAME" = "passbolt";
    };
    volumes = [
      "passbolt_gpg_volume:/etc/passbolt/gpg:rw"
      "passbolt_jwt_volume:/etc/passbolt/jwt:rw"
    ];
    ports = [
      "81:80/tcp"
      "444:443/tcp"
    ];
    cmd = [ "/usr/bin/wait-for.sh" "-t" "0" "db:3306" "--" "/docker-entrypoint.sh" ];
    dependsOn = [
      "passbolt-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=passbolt"
      "--network=passbolt_default"
    ];
  };
  systemd.services."podman-passbolt-passbolt" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-passbolt_default.service"
      "podman-volume-passbolt_gpg_volume.service"
      "podman-volume-passbolt_jwt_volume.service"
    ];
    requires = [
      "podman-network-passbolt_default.service"
      "podman-volume-passbolt_gpg_volume.service"
      "podman-volume-passbolt_jwt_volume.service"
    ];
    partOf = [
      "podman-compose-passbolt-root.target"
    ];
    wantedBy = [
      "podman-compose-passbolt-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-passbolt_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f passbolt_default";
    };
    script = ''
      podman network inspect passbolt_default || podman network create passbolt_default
    '';
    partOf = [ "podman-compose-passbolt-root.target" ];
    wantedBy = [ "podman-compose-passbolt-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-passbolt_database_volume" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect passbolt_database_volume || podman volume create passbolt_database_volume
    '';
    partOf = [ "podman-compose-passbolt-root.target" ];
    wantedBy = [ "podman-compose-passbolt-root.target" ];
  };
  systemd.services."podman-volume-passbolt_gpg_volume" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect passbolt_gpg_volume || podman volume create passbolt_gpg_volume
    '';
    partOf = [ "podman-compose-passbolt-root.target" ];
    wantedBy = [ "podman-compose-passbolt-root.target" ];
  };
  systemd.services."podman-volume-passbolt_jwt_volume" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect passbolt_jwt_volume || podman volume create passbolt_jwt_volume
    '';
    partOf = [ "podman-compose-passbolt-root.target" ];
    wantedBy = [ "podman-compose-passbolt-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-passbolt-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
